sudo: required

# install copy of docker on travis
services:
  - docker

# commands to be run before tests run
before_install:
  - docker build -t moetion/docker-react -f Dockerfile.dev .

# run commands to test (override default commands)
# add -- --coverage to exit automatically
script:
  - docker run moetion/docker-react npm run test -- --coverage

# AWS deployment
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-827576790373"
  bucket_path: "docker-react"
  #only deploy to AWS when push is made to master
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
