version: '3'
services:
  web:
    build:
      #where we want files and folders to be pulled for the image
      context: .
      #docker file name
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      #where we want files and folders to be pulled for the image
      context: .
      #docker file name
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
